### ISSUE TITLE
Error: Unable to access Inf2 metadata service

### ISSUE THREAD

**Issue by CambioML** [CambioML/uniflow-llm-text-data-cleaning-cluster#167]
TLDR
I am running the script [huggingface_model_neuron.ipynb](https://github.com/CambioML/uniflow/blob/main/example/transform/huggingface_model_neuron.ipynb) on AWS EC2 Inf2.xlarge and running client.run() returns `Neuron model can only run on the AWS EC2 inf2 instance series.`

Tracing through the `neuron_utils.py` code, it seems that `get_instance_type()` not returns 200.

---
On terminal:
```
ubuntu@ip-172-31-0-162:~/uniflow$ neuron-ls
instance-type: inf2.xlarge
instance-id: i-0927e14c03abb4ba5
+--------+--------+--------+---------+
| NEURON | NEURON | NEURON |   PCI   |
| DEVICE | CORES  | MEMORY |   BDF   |
+--------+--------+--------+---------+
| 0      | 2      | 32 GB  | 00:1e.0 |
+--------+--------+--------+---------+
```

Run `huggingface_model_neuron.ipynb`:

```
config = TransformHuggingFaceConfig(
    prompt_template=guided_prompt,
    model_config=HuggingfaceModelConfig(batch_size=4, model_name='mistralai/Mistral-7B-Instruct-v0.2', neuron=True))
client = TransformClient(config)
```

Returns 
<img width="868" alt="image" src="https://github.com/CambioML/uniflow/assets/134244177/8badd997-de8a-4b79-9e7a-8fc55e32f1d5">

**Comment by goldmermaid** [comment]
resolved by PR #171
