### ISSUE TITLE
huggingface_model_neuron failed on inf2.8x with batch_size= 1 or 2 

### ISSUE THREAD

**Issue by yfgit2012** [CambioML/uniflow-llm-text-data-cleaning-cluster#179]
code: uniflow-llm-text-data-cleaning-cluster/example/transform/huggingface_model_neuron.ipynb
Error message
[{'error': '(256, 4)',
  'traceback': 'Traceback (most recent call last):\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/uniflow/flow/server.py", line 159, in _run_flow\n    output = f(input_list)\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/uniflow/flow/flow.py", line 36, in __call__\n    nodes = self.run(nodes)\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/uniflow/flow/transform/transform_huggingface_flow.py", line 45, in run\n    return self._model_op(nodes)\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/uniflow/op/model/model_op.py", line 40, in __call__\n    value_dict = self._model.run(value_dict)\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/uniflow/op/model/abs_llm_processor.py", line 72, in run\n    data = self._model_server(serialized_data)\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/uniflow/op/model/model_server.py", line 469, in __call__\n    data = self._pipeline(data)\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/uniflow/op/model/neuron_utils.py", line 283, in neuron_infer\n    sample_output = model.generate(\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/transformers_neuronx/generation_utils.py", line 45, in generate\n    return super().generate(*args, **kwargs)\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context\n    return func(*args, **kwargs)\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/transformers/generation/utils.py", line 1525, in generate\n    return self.sample(\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/transformers/generation/utils.py", line 2622, in sample\n    outputs = self(\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n    return forward_call(*input, **kwargs)\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/transformers_neuronx/generation_utils.py", line 33, in forward\n    out_logits = self.model(input_ids, cache_ids, start_ids)\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n    return forward_call(*input, **kwargs)\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/transformers_neuronx/mistral/model.py", line 144, in forward\n    logits = self._forward(hidden, cache_ids, start_ids, last_token_id, curr_window_start, neuron_config=self.neuron_config)\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/transformers_neuronx/base.py", line 358, in _forward\n    logits = self.context(hidden, *args, neuron_config=neuron_config)\n  File "/home/ec2-user/aws_neuron_venv_pytorch/lib64/python3.9/site-packages/transformers_neuronx/base.py", line 188, in context\n    model = self.decoder_lm_head_for_context[estimate, batch_size]\nKeyError: (256, 4)\n'},
...

**Comment by goldmermaid** [comment]
hi @yfgit2012 , thanks for submitting the issue. we solved it in PR #183
